name: build

on: [push]



jobs:
  ubuntu-18-04:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@master
    - name: Install-prerequisites
      run: sudo ./scripts/InstallPrerequisites-Ubuntu.sh
    - name: Build-ubuntu-18.04
      run: |
        lsb_release -a
        mkdir shasta-build
        cd shasta-build 
        cmake .. -DBUILD_NATIVE=OFF -DBUILD_ID="Shasta unreleased test build newer than release 0.3.0"
        make -j 2 all
        make install/strip
        mv shasta-install shasta-Ubuntu-18.04
        tar -cvf shasta-Ubuntu-18.04.tar shasta-Ubuntu-18.04        
    - name: Test-ubuntu-18.04
      run: 
        cd ..
        sudo apt install gzip
        gunzip shasta/test/TinyTest.fasta.gz
        shasta-build/shasta-install/bin/shasta --input shasta/test/TinyTest.fasta
        ls -l ShastaRun/Assembly.fasta
    - uses: actions/upload-artifact@master
      with:
        name: shasta-Linux
        path: shasta-build/shasta-Ubuntu-18.04/bin/shasta
    - uses: actions/upload-artifact@master
      with:
        name: shasta-Ubuntu-18.04.tar
        path: shasta-build/shasta-Ubuntu-18.04.tar



  ubuntu-16-04:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@master
    - name: Install-prerequisites
      run: sudo ./scripts/InstallPrerequisites-Ubuntu.sh
    - name: Build-ubuntu-16.04
      run: |
        lsb_release -a
        mkdir shasta-build
        cd shasta-build 
        cmake .. -DBUILD_NATIVE=OFF -DBUILD_ID="Shasta unreleased test build newer than release 0.3.0"
        make -j 2 all
        make install/strip
        mv shasta-install shasta-Ubuntu-16.04
        tar -cvf shasta-Ubuntu-16.04.tar shasta-Ubuntu-16.04        
    - uses: actions/upload-artifact@master
      with:
        name: shasta-OldLinux
        path: shasta-build/shasta-Ubuntu-16.04/bin/shasta
    - uses: actions/upload-artifact@master
      with:
        name: shasta-Ubuntu-16.04.tar
        path: shasta-build/shasta-Ubuntu-16.04.tar


       
  macOS-10-14:

    runs-on: macOS-10.14

    steps:
    - uses: actions/checkout@master
    - name: Install-prerequisites
      run: scripts/InstallPrerequisites-macOS.sh
    - name: Build-macOS-10.14
      run: |
        mkdir shasta-build
        cd shasta-build 
        cmake .. -DBUILD_NATIVE=OFF -DBUILD_ID="Shasta unreleased test build newer than release 0.3.0"
        make VERBOSE=1 -j 2 all
        make install/strip
    - uses: actions/upload-artifact@master
      with:
        name: shasta-macOS
        path: shasta-build/shasta-install/bin/shasta


