name: macOS-10.14

on: [push]

jobs:
  build:

    runs-on: macOS-10.14

    steps:
    - uses: actions/checkout@master
    - name: Install-prerequisites
      run: scripts/InstallPrerequisites-macOS.sh
    - name: Build-macOS-10.14
      run: |
        mkdir shasta-build
        cd shasta-build 
        cmake ..
        make VERBOSE=1 all
        make install


