name: UbuntuBuild

on: [push]

jobs:
  build:

#    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]
    
    steps:
    - uses: actions/checkout@master
    - name: Install prerequisites
      run: sudo ./scripts/InstallPrerequisites-Ubuntu.sh
    - name: Build
      run: |
        lsb_release -a
        mkdir shasta-build
        cd shasta-build 
        cmake ..
        make all
        make install


