name: ubuntu-18.04

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@master
    - name: Install-prerequisites
      run: sudo ./scripts/InstallPrerequisites-Ubuntu.sh
    - name: Build-ubuntu-18.04
      run: |
        lsb_release -a
        mkdir shasta-build
        cd shasta-build 
        cmake .. -DBUILD_ID="Shasta test build newer than release 0.1.0, built on Ubuntu 18.04."
        make all
        make install/strip


